1.넘파이 설치 확인

In [1]:
import numpy as np
print(np.__version__)

2.0.2


2. 넘파이 배열 (ndarray) 생성과 속성 확인

In [2]:
a1 = np.array([1,2,3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
 #ndim: 차원 개수, shape: 차원 크기를 튜플로)
a2 = np.array((1,2,3))
print(a2, type(a2), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [4]:
a3 = np.array([[1,2,3], [4,5,6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape,a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [ ]:
a4 = np.array([1,2,3],dtype=float)
print(a4, type(a4), a4.dtype, a4.ndim, a4.shape, a4.size)
a5 = np.array([1, 2, 3], float)

In [ ]:
a5 = np.array([1,2,3],float)
print(a3, type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

In [ ]:
a6 = np.array([1,4,5,'8'])
print(a6)
print(type(a6),a6.dtype,a6.ndim,a6.shape,a6.size)

In [ ]:
a7 = np.array([1,4,5,'8'],int)
print(a7)
print(type(a7),a7.dtype,a7.ndim,a7.shape,a7.size)

In [5]:
test_list = [[1,4,5,8],[1,4,5]]
np.array(test_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

3. Indexing

In [ ]:
d = np.array([1,2,3,4,5,6,7,8,9])
print(d[0],d[1],d[2],d[-1],d[-2])

d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0][0]) # 배열명[행][열] 형태
print(d2[0, 0]) # 배열명[행, 열] 형태
print(d2[1, 1])
print(d2[1, -1])

d3 = np.arange(12).reshape(2, 2, 3)
print(d3[0][0][0]) # 배열명[면][행][열] 형태
print(d3[0, 0, 0]) # 배열명[면, 행, 열] 형태
print(d3[1, 1, 2])
print(d3[-1, -1, -1])
print(d3)

In [ ]:
d = np.array([1,2,3,4,5,6,7,8,9])
print(d)
print(d[2:3],d[:],d[:-1])
print(d[::2],d[::-1])

4. Slicing

In [ ]:
d2 =np.array([1,2,3,4,5],[6,7,8,9,10]])
print(d2[0])
print(d2[0,:])
print(d2[:,:-1])
print(d2[::2,::2])

In [6]:
d2 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(d2)
print(d2[::1,::2])
d2[::1,::2] = 30
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  3  5]
 [ 6  8 10]]
[[30  2 30  4 30]
 [30  7 30  9 30]]


In [ ]:
d2[:,:] = -1
print(d2)

In [ ]:
d3 = np.arange(12).reshape(2,2,3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

5.Boolean Indexing

In [ ]:
data = np.array([4,6,7,3,2,0])
print(data > 3)
print(data[data >3])

In [ ]:
f = np.array([4,6,7,3,2])
indexes = np.array([1,2,0,2,2,2])
f[indexes]

In [ ]:
f2 = np.array([[1,4],[9,16]])
x = np.array([0,1,1,1,0,0])
y = np.array([0,0,0,1,1,1])
f2[x,y]

In [ ]:
print(data[(data > 3) & (data < 6)])
print(data[data % 2 ==0])
print(data[data < data.mean()])

6. 팬시 인덱싱(Fancy indexing)

In [ ]:
f = np.array([4,6,7,3,2])
indexes = np.array([1,2,0,2,2,2])
f[indexes]

In [ ]:
f2 = np.array([[1,4],[9,16]])
x = np.array([0,1,1,1,0,0])
y = np.array([0,0,0,1,1,1])
f2[x,y]

7. 넘파이 배열의 정렬

In [ ]:
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

In [ ]:
numbers.sort()
print(numbers)

In [ ]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1],
                 [10,9,12,11]])
print(arr2d)

print(np.sort(arr2d))
print(np.sort(arr2d,axis=1))
print(np.sort(arr2d,axis=0))

In [ ]:
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

In [ ]:
# [연습 문제] 성적 순으로 출력 (내림차순)
names =np.array(['John','Mike','Sarah','Kate','Samuel'])
scores = np.array([78,95,84,98,88])

scores_sorted_index = np.argsort(scores)[::1]
print(scores_sorted_index)

8. 넘파이 배열의 사칙연산

In [3]:
x = np.arange(1,7).reshape(2,3)
x + x
x + 2
y = np.array([10,20,30])
x + y

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
# 넘파이 배열의 주요 연산 함수
array_01 = np.arange(1, 13).reshape(4, 3)
array_02 = np.arange(13, 25).reshape(4, 3)
ndarray = array_01 + array_02

print(ndarray)
# 넘파이 배열의 sum, mean, max, min을 축을 따라 구하는 함수
print(ndarray.sum(axis = None))
print(ndarray.mean(axis = None))
print(ndarray.max(axis = None))
print(ndarray.min(axis = None))

# 넘파이 배열 데이터 중 max, min의 값이 있는 index 반환
print(ndarray.argmax(axis = None))
print(ndarray.argmin(axis = None))

# 배열 내부의 모든 값이 참일 떄는 True, 하나라도 참이 아닐 경우에는 False를 반환
# and 조건을 전체 요소에 적용
print(ndarray.all(axis = None))
print(np.all(ndarray, axis = None))

print(np.all(ndarray < 3))

print(ndarray.any(axis = None))
print(np.any(ndarray, axis = None))

print(np.any(ndarray < 4))

9. any().all() 함수의 활용

In [ ]:
# 1. 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1,2,np.nan,4])
print(np.any(np.isnan(data))) # True
# 2.두 배열이 완전히 동일한지 확인
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.all(arr1 == arr2))